package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/IlyushaChic/financial-platform/backend/api-gateway/internal/graphql/generated"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string, fullName string) (*generated.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Register - register"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*generated.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Transfer is the resolver for the transfer field.
func (r *mutationResolver) Transfer(ctx context.Context, toAccountID string, amount float64, currency string, description *string) (*generated.Transaction, error) {
	panic(fmt.Errorf("not implemented: Transfer - transfer"))
}

// Deposit is the resolver for the deposit field.
func (r *mutationResolver) Deposit(ctx context.Context, accountID string, amount float64, currency string, description *string) (*generated.Transaction, error) {
	panic(fmt.Errorf("not implemented: Deposit - deposit"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*generated.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Balance is the resolver for the balance field.
func (r *queryResolver) Balance(ctx context.Context, accountID string) (*generated.Account, error) {
	panic(fmt.Errorf("not implemented: Balance - balance"))
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, limit *int, offset *int) ([]*generated.Transaction, error) {
	panic(fmt.Errorf("not implemented: Transactions - transactions"))
}

// TransactionCompleted is the resolver for the transactionCompleted field.
func (r *subscriptionResolver) TransactionCompleted(ctx context.Context) (<-chan *generated.Transaction, error) {
	panic(fmt.Errorf("not implemented: TransactionCompleted - transactionCompleted"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
